baseurl = "https://john-qu.netlify.com/"
languageCode = "en-us"
title = "John Qu | 曲政"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
enableEmoji = true
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
rssLimit = 100

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
    cn = "/cn/:year/:month/:slug/"
    en = "/en/:year/:month/:slug/"

#[[menu.main]]
#    name = "Home"
#    url = "/"
#    weight = 1
[[menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 2
[[menu.main]]
    name = "关于"
    url = "/cn/about/"
    weight = 3
[[menu.main]]
    name = "日志"
    url = "/cn/"
    weight = 4
[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.en]]
    name = "About"
    url = "/en/about/"
    weight = 2
[[menu.en]]
    name = "Blog"
    url = "/en/"
    weight = 3
[[menu.en]]
    name = "Categories"
    url = "/categories/"
    weight = 4
[[menu.en]]
    name = "Tags"
    url = "/tags/"
    weight = 5
[[menu.en]]
    name = "中文"
    url = "/cn/"
    weight = 6
#[[menu.main]]
#    name = "Subscribe"
#    url = "/index.xml"
[[menu.cn]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.cn]]
    name = "关于"
    url = "/cn/about/"
    weight = 2
[[menu.cn]]
    name = "日志"
    url = "/cn/"
    weight = 3
[[menu.cn]]
    name = "分类"
    url = "/categories/"
    weight = 4
[[menu.cn]]
    name = "标签"
    url = "/tags/"
    weight = 5
[[menu.cn]]
    name = "English"
    url = "/en/"
    weight = 6

[params]
    description = "Reflection in Transition"
    footer = "&copy; [John Qu](https://john-qu.netlify.com) 2019 | [Github](https://github.com/john-qu)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "python"]
  highlightjsTheme = "github"

[params.valine]
    enable = true
    appId = 'DmxYx3PkAOKtKsw1N25DeH3A-gzGzoHsz'
    appKey = 'x3DJDBP168lRURzRo4OBn3cH'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'identicon'
    placeholder = '说点什么吧...'
    visitor = false
